package com.jaeg6.launchpads;

        import org.bukkit.ChatColor;
        import org.bukkit.Location;
        import org.bukkit.Material;
        import org.bukkit.block.Block;
        import org.bukkit.command.Command;
        import org.bukkit.command.CommandSender;
        import org.bukkit.entity.Player;
        import org.bukkit.plugin.PluginManager;
        import org.bukkit.plugin.java.JavaPlugin;
        import org.bukkit.util.Vector;

        import java.util.ArrayList;

        import static org.bukkit.Bukkit.getWorld;

public class Main extends JavaPlugin
{
    //To store the current locations of activated launchpads
    public ArrayList<String> locations = new ArrayList<>();

    //To store the velocity direction/power properties
    public ArrayList<Vector> vectors = new ArrayList<>();

    @Override
    public void onEnable()
    {
        getLogger().info("LaunchPads enabled!");

        //register listener
        PluginManager pm = getServer().getPluginManager();
        Listener listener = new Listener(this);
        pm.registerEvents(listener, this);

        getConfig().options().header("DO NOT EDIT THIS FILE" +
                "\nEditing the contents in this file WILL corrupt the launchpad data" +
                "\nShould something happen to this file, reload the server");

        if (!(getConfig().get("locations") == null))
        {
            locations = (ArrayList<String>) getConfig().get("locations");
            saveConfig();
        }

        if (!(getConfig().get("vectors") == null))
        {
            vectors = (ArrayList<Vector>) getConfig().get("vectors");
            saveConfig();
        }

    }

    @Override
    public void onDisable()
    {
        getLogger().info("LaunchPads disabled!");

        getConfig().set("locations", locations);
        getConfig().set("vectors", vectors);
        saveConfig();
    }

    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args)
    {
        try
        {
            if (sender instanceof Player)
            {

                Player player = (Player) sender;

                //command executed by player
                String lowerCmd = cmd.getName().toLowerCase();

                if (lowerCmd.equals("lup"))
                {
                    //launchpad command
                    //Check to make sure player is looking at a pressure plate, and one of the commands was executed correctly.
                    Block b = player.getTargetBlock(null, 100);
                    if (b.getBlockData().getMaterial().equals(Material.LIGHT_WEIGHTED_PRESSURE_PLATE)
                            && (args.length == 1 && (args[0].toLowerCase().equals("clear") || args[0].toLowerCase().equals("check"))
                            || (args.length == 4 && args[0].toLowerCase().equals("set"))))
                    {
                        System.out.println("Arguments found: " + args.length);

                        switch (args[0].toLowerCase())
                        {
                            case "set":
                                //Set selected pressure plate to be a launchpad
                                //If selected plate is already a launchpad; overwrite the old properties.

                                //set command
                                if (setLaunchpad(b.getLocation(), Double.parseDouble(args[1]), Double.parseDouble(args[2]), Double.parseDouble(args[3])))
                                {
                                    sender.sendMessage(ChatColor.GREEN + "Launchpad created successfully! (overwrote old properties)");
                                }
                                else
                                {
                                    sender.sendMessage(ChatColor.GREEN + "Launchpad successfully!");
                                }
                                sender.sendMessage((ChatColor.GRAY + "" + ChatColor.ITALIC + "Velocity vectors: X: " + args[1] + ", Y: " + args[2] + ", Z: " + args[3]));
                                return true;

                            case "clear":
                                //search for pressure plate and clear its properties, making it a normal pressure plate again

                                //clear command
                                if (removeLaunchpad(b.getLocation()))
                                {
                                    sender.sendMessage(ChatColor.GREEN + "Launchpad properties cleared!");
                                    sender.sendMessage((ChatColor.GRAY + "Cleared at: X: " + b.getLocation().getBlockX() + ", Y: " + b.getLocation().getBlockY() + ", Z: " + b.getLocation().getBlockZ()));
                                }
                                else
                                {
                                    sender.sendMessage(ChatColor.YELLOW + "No launchpad data found at this position!");
                                }
                                return true;

                            case "check":
                                //Search through arraylist/config for target plate's velocity properties
                                isLaunchpad(player, b.getLocation());

                                return true;

                            default:
                                sender.sendMessage(ChatColor.DARK_RED + "Error: " + ChatColor.RED + "invalid arguments");
                                sender.sendMessage(ChatColor.RED + "Try /<command> <set> <x> <y> <z>");
                                return true;
                        }
                    }
                    else
                    {
                        sender.sendMessage(ChatColor.DARK_RED + "Error: " + ChatColor.RED + "please make sure you're looking at a gold pressure plate");
                        sender.sendMessage(ChatColor.RED + "and check your arguments: /<command> <set/clear/check> <x> <y> <z>");
                    }
                    return true;
                }
                else
                {
                    //should use a default "command not recognized" here
                    return true;
                }
            }
            else if (cmd.getName().toLowerCase().equals("lupdebug"))
            {
                System.out.println("\nLocations isEmpty: " + locations.isEmpty()
                        + "\n" + "Vectors isEmpty: " + vectors.isEmpty());

                return true;
            }
            else
            {
                System.err.println("This command can only be executed by a player.");
                return true;
            }
        }
        catch (NumberFormatException e)
        {
            //Player put non number values as vector arguments
            sender.sendMessage(ChatColor.DARK_RED + "Error: " + ChatColor.RED + "one or more vector arguments is not an actual number.");
            return true;
        }
    }

    /**
     *
     * @param location location data for new launchpad
     * @param x vector x
     * @param y vector y
     * @param z vector z
     * @return True if location/vector data already exist, false if new location/vector data was and added
     */
    public boolean setLaunchpad(Location location, double x, double y, double z)
    {
        Vector vector;
        //check to make sure location is vacant
        for(int i = 0; i < locations.size(); i++)
        {
            if(stringToLoc(locations.get(i)).getX() == location.getX()
            && stringToLoc(locations.get(i)).getY() == location.getY()
            && stringToLoc(locations.get(i)).getZ() == location.getZ()
            && stringToLoc(locations.get(i)).getWorld() == location.getWorld())
            {
                //location exists
                //overwrite location
                locations.set(i, locToString(location));

                //create/overwrite new vector
                vector = new Vector();
                vector.setX(x);
                vector.setY(y);
                vector.setZ(z);

                vectors.set(i, vector);

                getConfig().set("locations", locations);
                getConfig().set("vectors", vectors);
                saveConfig();
                return true;
            }
        }
        //location not found or list is empty
        //add location and vector
        locations.add(locToString(location));

        vector = new Vector();
        vector.setX(x);
        vector.setY(y);
        vector.setZ(z);

        vectors.add(vector);

        getConfig().set("locations", locations);
        getConfig().set("vectors", vectors);
        saveConfig();
        return false;
    }

    /**
     *
     * @param location location of launchpad to remove
     * @return true if location found and removed, else false
     */
    public boolean removeLaunchpad(Location location)
    {
        for(int i = 0; i < locations.size(); i++)
        {
            if(stringToLoc(locations.get(i)).getX() == location.getX()
            && stringToLoc(locations.get(i)).getY() == location.getY()
            && stringToLoc(locations.get(i)).getZ() == location.getZ()
            && stringToLoc(locations.get(i)).getWorld() == location.getWorld())
            {
                //location found, remove the properties
                locations.remove(i);
                vectors.remove(i);

                getConfig().set("locations", locations);
                getConfig().set("vectors", vectors);
                saveConfig();
                return true;
            }
        }
        return false;
    }

    /**
     * method used for check command to give player details about the launchpad's properties
     * @param player player that called the command
     * @param location location to check
     */
    public void isLaunchpad(Player player, Location location)
    {
        for(int i = 0; i < locations.size(); i++)
        {
            if(stringToLoc(locations.get(i)).getX() == location.getX()
                    && stringToLoc(locations.get(i)).getY() == location.getY()
                    && stringToLoc(locations.get(i)).getZ() == location.getZ()
                    && stringToLoc(locations.get(i)).getWorld() == location.getWorld())
            {
                //location found
                player.sendMessage(ChatColor.GREEN + "Launchpad data found!");
                player.sendMessage(ChatColor.GRAY + "Properties: X: " + vectors.get(i).getX() + ", Y: " + vectors.get(i).getY() + ", Z: " + vectors.get(i).getZ());
                return;
            }
        }
        player.sendMessage(ChatColor.YELLOW + "No Launchpad data found.");
    }

    /**
     * method used for check to see if this is a launchpad to then launch the player
     * @param location location to check
     * @return Vector properties for located launchpad
     */
    public Vector isLp(Location location)
    {
        Vector vector;
        for(int i = 0; i < locations.size(); i++)
        {
            if(stringToLoc(locations.get(i)).getX() == location.getX()
                    && stringToLoc(locations.get(i)).getY() == location.getY()
                    && stringToLoc(locations.get(i)).getZ() == location.getZ()
                    && stringToLoc(locations.get(i)).getWorld() == location.getWorld())
            {
                //launchpad found
                vector = vectors.get(i);
                return vector;
            }
        }
        //not a launchpad
        return null;
    }

    /**
     *
     * @param loc location to convert
     * @return converted location to string
     */
    public static String locToString(Location loc){
        return loc.getWorld().getName() + "!" + loc.getX() + "!" + loc.getY() + "!" + loc.getZ() + "!" + loc.getYaw() + "!" + loc.getPitch();
    }

    /**
     *
     * @param str string to convert
     * @return converted string to location
     */
    public static Location stringToLoc(String str){
        return new Location(getWorld(str.split("!")[0]), Double.parseDouble(str.split("!")[1]), Double.parseDouble(str.split("!")[2]), Double.parseDouble(str.split("!")[3]), Float.parseFloat(str.split("!")[4]), Float.parseFloat(str.split("!")[5]));
    }
}
